# Fluent UI; back_color: C0BFC0; fore_color: 41495B; input_color: E1E9FB; back_text_color: FFFFFF; fore_text_color: FFFFFF; input_text_color: 000000; blank_color: FFFFFF; blank_text_color: 000000; arc_fore_color: 21293B; arc_input_color: C1C9DB; radius: 7; box_shadow: 0; gradient_deg: 180; gloss: 1;
# Windows 11; opacity: 64; background: metro.win11.00.png; avatar: windows;
# Playlist; lock_music: orchestra;
# Segoe UI Font; font_ascii: seguisb.ttf; font_latin: seguisb.ttf; font_phone: l_10646.ttf; font_greek: seguisb.ttf; font_cyril: seguisb.ttf; font_arabi: arialuni.ttf; font_korea: arialuni.ttf; font_china: arialuni.ttf; font_other: arialuni.ttf; font_emoji: seguiemj.ttf;
# Ribbon; theme: fluent; menu: file_finder,browse_europedia,preferences,visual_effects,text_editor,localization,user_accounts,statistics,personalization,news_feed,volume_control,media_player; icons: 1; faceoff: 1;
# Isolate; lock_background: metro; lock_avatar: avatar; lock_font: windows; lock_sound: unix;